name: CPPCheck
'on':
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
jobs:
  build:
    name: cppcheck
    runs-on: '${{ matrix.os }}'
    strategy:
      matrix:
        os:
          - ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: cppcheck
        uses: deep5050/cppcheck-action@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          other_options: --suppress=missingIncludeSystem --error-exitcode=1
      - name: upload_results
        if: success() || failure()
        uses: actions/upload-artifact@v3
        with:
          name: cppcheck_report
          path: cppcheck_report.txt
      # - name: publish report
      #   uses: mikeal/publish-to-github-action@master
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     BRANCH_NAME: ${{ github.ref_name }}
